spring.application.name=trade-login-service



spring.datasource.url=jdbc:mysql://localhost:3306/trade_login_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

#hibernate.hbm2ddl.auto=update